#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#       For example: SHELL=/bin/bash ./gradlew
#
#   (2) The slashes in the paths are important on Windows (forward slashes)
#       and should not be swapped out for backslashes.
#
##############################################################################

if [ "$(uname)" = "Darwin" ] ; then
    APP_NAME="Gradle"
    APP_CYGWIN=false
else
    APP_NAME="Gradle"
    APP_CYGWIN=true
fi

APP_HOME="$(cd "$(dirname "$0")" && pwd -P)"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
JAVACMD="$JAVA_HOME/bin/java"
if [ ! -x "$JAVACMD" ] ; then
    JAVACMD=java
fi
export APP_HOME CLASSPATH JAVACMD
exec "$JAVACMD" -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
